@startuml
class LoginEntity {
    -serialVersionUID = 1L: long
    -user: UserEntity
    -password: PasswordEntity
    -active: Boolean  
}

class RelLoginGroupEntity {
    -serialVersionUID = 1L: long
    -login: LoginEntity
    -group: GroupEntity
}

class GroupEntity {
    -serialVersionUID = 1L: long
    -name: String
    -description: String
}

class PasswordEntity {
    -serialVersionUID = 1L: long
    -encryptedPassword: String
} 

class UserEntity {
    -serialVersionUID = 1L: long
    -parent: UserEntity
    -firstname: String
    -lastname: String
    -email: String
    -validatedEmail: Boolean
    -cellphone: String
    -validatedCellphone: Boolean
    -description: String
    -photo_external_id: Long
}

class TokenOwnerEntity {
    -serialVersionUID = 1L: long
    -user: UserEntity
    -key: String
    -subkeyUserCountLimit: Integer
    -parentMustBeAccepted: Boolean
}

class SunEcityToken {
    -parent: SunEcityToken;
    -uuid: String
    -tokenOwner: TokenOwnerEntity
    -map: MapEntity
    -exceptionMessageLocation: String
    -timeWindow: TimeWindowEntity 
    -exceptionMessageTimewindow: String
    -device: DeviceEntity
    -action: AreaAction
    -signalType: SignalType
    -offline: Boolean
}
 
class MapEntity {
    -serialVersionUID = 1L: long
    -idUser: Long
    -uuid: String
    -name: String
    -jsonStyle: String
    -geojson: String  ** RFC 7946 **
    -description: String
}

class DeviceEntity {
    -serialVersionUID = 1L: long
    -idUser: Long
    -uuid: String
    -name: String
    -jsonStyle: String
    -description: String
}

class TimeWindowEntity {
    -name: String
	-cronExpression: String
    -description: String
}

class SignalPermissionEntity {
    -tokenOwner: TokenOwnerEntity
    -signal: SignalType
	-permission: Boolean
    -description: String
}

class AreaActionPermissionEntity {
    -tokenOwner: TokenOwnerEntity
    -action: AreaAction
	-permission: Boolean
    -description: String
}

enum AreaAction{
    ENTERED,
    EXITED,
    WAS_INSIDE,
    FIXED_TIME,
}


enum SignalType{
    VDI,
    RING,
    DOOR_OPENER,
    NOTOFICATION,
}

RelLoginGroupEntity "1..n" --> "1" GroupEntity
RelLoginGroupEntity "1..n" --> "1" LoginEntity
LoginEntity "1" --> "1" UserEntity
LoginEntity "1" --> "1" PasswordEntity
TokenOwnerEntity "1..n" --> "1" UserEntity
SunEcityToken "1" *--> "1" MapEntity
SunEcityToken "1" o--> "1" DeviceEntity
SunEcityToken "1..n" --> "1" SunEcityToken
SunEcityToken "1..n" --> "1" TokenOwnerEntity
SignalPermissionEntity "1..n" --> "1" TokenOwnerEntity
AreaActionPermissionEntity "1..n" --> "1" TokenOwnerEntity
SunEcityToken "1" *--> "1" TimeWindowEntity
SunEcityToken .-> AreaAction
SunEcityToken .-> SignalType
SignalPermissionEntity .-> SignalType
AreaActionPermissionEntity .-> AreaAction
@enduml